spring:
  application:
    name: twitter-consumer-elastic-search
  data:
    mongodb:
      host: mongo-0.mongo.default.svc.cluster.local,mongo-1.mongo.default.svc.cluster.local,mongo-2.mongo.default.svc.cluster.local
      port: 27017
      database: twitter-posts
