/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservices.twitter_consumer_elastic_search.kafka.model;

import lombok.Data;
import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@Data
public class TwitterAvroModel {
  private Long userId;
  private String id;
  private String text;
  private Long createdAt;
}










