/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.microservices.twitter_consumer_elastic_search.kafka.model;

import lombok.Data;

@Data
public class TwitterAvroModel {
  private Long userId;
  private String id;
  private String text;
  private String createdAt;
}










